# Generated by Django 5.2.8 on 2026-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
