# Generated by Django 6.0.1 on 2026-01-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
